config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  namespace :api, defaults: { format: 'json' } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      
      get 'tag/:tag', to: 'bundles#index', as: :tag
      get 'tags', to: 'tags#index'
      resources :bundles
    end
  end
  
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  
  resources :bundles do
    resources :links
  end

  root 'bundles#index'

end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base

	before_create :generate_access_token

	private

		def generate_access_token
		  begin
		    self.access_token = SecureRandom.hex
		  end while self.class.exists?(access_token: access_token)
		end

end

app/models/bundle.rb
class Bundle < ActiveRecord::Base
	acts_as_taggable

	has_many :links

	validates_presence_of :name
	validates_uniqueness_of :name
end

app/models/link.rb
class Link < ActiveRecord::Base
	belongs_to :bundle
	validates_presence_of :name
	validates_presence_of :url
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates_uniqueness_of :email
	validates_presence_of :full_name

	def full_name
		[ first_name, last_name ].join(' ')
	end

	def full_name=(name)
  	split = name.split(' ', 2)
  	self.first_name = split.first
  	self.last_name = split.last
	end

	def role_name
		case self.role
			when 0 then "Admin"
			else "User"
		end
	end

end

app/controllers/api/base_controller.rb
module Api
	class BaseController < ApplicationController

		skip_before_action :verify_authenticity_token
		before_action :authorize

		private

		def authorize
			authenticate_or_request_with_http_token do |token, options|
				ApiKey.exists?(access_token: token)
  		end
		end

	end
end

app/controllers/api/v1/bundles_controller.rb
module Api
	module V1
    class BundlesController < Api::BaseController
			  		
  		def index
        @bundles = params[:tag] ? Bundle.tagged_with(params[:tag]) : Bundle.all
  		end

      def show
        @bundle = Bundle.find(params[:id])
      end

      private

        def bundle_params
          params.require(:bundle).permit(:name, :tag_list)
        end

		end # BundlesController
  end # V1
end # Api

app/controllers/api/v1/tags_controller.rb
module Api
	module V1
    class TagsController < Api::BaseController
			  		
  		def index
        @tags = ActsAsTaggableOn::Tag.all
  		end

		end # TagsController
  end # V1
end # Api

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  helper_method :current_user

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def authorize
  	redirect_to login_url, alert: "Not authorized" if current_user.nil?
	end

end

app/controllers/bundles_controller.rb
class BundlesController < ApplicationController
  before_action :authorize
  before_action :set_bundle, only: [:show, :edit, :update, :destroy]

  def index
    @bundles = Bundle.all
  end

  def show
    @link = Link.new
  end

  def new
    @bundle = Bundle.new
  end

  def edit
  end

  def create
    @bundle = Bundle.new(bundle_params)

    respond_to do |format|
      if @bundle.save
        format.html { redirect_to @bundle, notice: 'Bundle was successfully created.' }
        format.json { render :show, status: :created, location: @bundle }
      else
        format.html { render :new }
        format.json { render json: @bundle.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @bundle.update(bundle_params)
        format.html { redirect_to @bundle, notice: 'Bundle was successfully updated.' }
        format.json { render :show, status: :ok, location: @bundle }
      else
        format.html { render :edit }
        format.json { render json: @bundle.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @bundle.destroy
    respond_to do |format|
      format.html { redirect_to bundles_url, notice: 'Bundle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_bundle
      @bundle = Bundle.find(params[:id])
    end

    def bundle_params
      params.require(:bundle).permit(:name, :tag_list)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  
  before_action :authorize
  before_action :set_bundle
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  def index
    @links = @bundle.links.all
  end
  
  def show
  end
  
  def new
    @link = @bundle.links.new
  end

  def edit
  end

  def create
    @link = @bundle.links.build(link_params)
    if @link.save
      redirect_to bundle_path(@bundle), notice: 'Link was successfully created.'
    else
      render :new
    end
  end

  def update
    if @link.update(link_params)
      redirect_to bundle_path(@bundle), notice: 'Link was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @link.destroy
    redirect_to bundle_links_path, notice: 'Link was successfully destroyed.'
  end

  private
    
    def set_bundle
      @bundle = Bundle.find(params[:bundle_id])
    end

    def set_link
      @link = @bundle.links.find(params[:id])
    end
    
    def link_params
      params.require(:link).permit(:name, :url, :bundle_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 
	def new
	end

	def create
	  user = User.find_by_email(params[:email])
	  if user && user.authenticate(params[:password])
	    session[:user_id] = user.id
	    redirect_to root_url
	  else
	    flash.now.alert = "Email or password is invalid"
	    render "new"
	  end
	end

	def destroy
	  session[:user_id] = nil
	  redirect_to root_url, notice: "Logged out!"
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authorize

	def index
		@users = User.all
	end

	def new
	  @user = User.new
	end

	def create
	  @user = User.new(user_params)
	  if @user.save
	    session[:user_id] = @user.id
	    redirect_to root_url, notice: "Thank you for signing up!"
	  else
	    render "new"
	  end
	end

	private

 		def user_params
  		params.require(:user).permit(:email, :password, :password_confirmation, :full_name)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def icon(name)
		content_tag :i, nil, class: "fa fa-#{name}"
	end

end

app/helpers/bundles_helper.rb
module BundlesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bundles/_form.html.erb
<%= form_for(@bundle) do |f| %>
  <% if @bundle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bundle.errors.count, "error") %> prohibited this bundle from being saved:</h2>

      <ul>
      <% @bundle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :tag_list, "Tags (seperated by commas)" %>
    <%= f.text_field :tag_list %>
  </div>

  <div class="actions">
    <%= f.submit nil, class: "button" %>
  </div>

<% end %>

app/views/bundles/edit.html.erb
<% content_for :header do %>
	<header>
		<h2>
			<%= icon 'bookmark-o' %> 
			<%= link_to 'Bundles', bundles_path %>
			<%= icon('angle-right') + @bundle.name %>
		</h2>
	</header>
<% end %>

<%= render 'form' %>

<hr>

<%= link_to 'Destroy', @bundle, method: :delete, data: { confirm: 'Are you sure?' } %> | 
<%= link_to 'Back', bundles_path %>

app/views/bundles/index.html.erb
<% content_for :header do %>
	<header>
		<h2><%= icon 'bookmark-o' %> Bundles</h2>
	</header>
<% end %>

<div class="cf">
	<% @bundles.each do |bundle| %>
		
		<div class="module">
			
			<div class="icon-container">
				<span class="count"><%= bundle.links.count %></span>
				<%= icon('folder-o') %>
			</div>

  		<h2><%= link_to bundle.name, bundle %></h2>

  		<span class="details">
  			<%= link_to icon('cog'), edit_bundle_path(bundle) %>
  			<%= icon('tag') %> 
  			<em><%= bundle.tag_list.join(', ') %></em>
  		</span>
  	
  	</div> <!--/.module -->
	<% end %>
</div> <!--./cf -->

<br>
<p><%= link_to icon('bookmark-o') + 'New Bundle', new_bundle_path, class: 'button' %></p>

app/views/bundles/new.html.erb
<% content_for :header do %>
	<header>
		<h2><%= icon 'bookmark-o' %> New Bundle</h2>
	</header>
<% end %>

<%= render 'form' %>

<hr>

<%= link_to icon('angle-left') + 'Back', bundles_path, class: "button" %>

app/views/bundles/show.html.erb
<% content_for :header do %>
	<header>
		<h2>
			<%= icon 'bookmark-o' %> 
			<%= link_to 'Bundles', bundles_path %>
			<%= icon('angle-right') + @bundle.name %>
		</h2>
	</header>
<% end %>

<div class="inline-form">
	<%= render 'links/form' %>
</div>

<br>

<div class="cf">
	<% @bundle.links.each do |link| %>
		
		<div class="module">
			
			<div class="icon-container">
				<%= icon('star-o') %>
			</div>

  		<h2><%= link_to link.name, edit_bundle_link_path(@bundle, link) %><br></h2>

  		<span class="details">
  			<em><%= link.url %></em>
  		</span>
  	
  	</div> <!--/.module -->
	<% end %>
</div> <!--./cf -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <title>Bookmarker</title>
  <link href="//cloud.typography.com/7685272/644722/css/fonts.css" rel="stylesheet" type="text/css" />
 	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="sidebar">
	
		<p><a href="<%= root_url %>"><img src="<%= asset_path "push.png" %>" class="logo"></a></p>

		<% if current_user %>
			<p class="info">Logged in as the<br>remarkable <%= current_user.full_name %>!</p>
			
			<nav>
				<%= link_to icon('bookmark-o') + "Bundles", bundles_path %>
				<%= link_to icon('users') + "Users", users_path %>
				<%= link_to icon('lock') + "Log Out", logout_path %>
			</nav>
		<% end %>

	</div> <!--/.sidebar -->

	<div class="main">
		
		<%= yield :header %>
		
		<% flash.each do |name, msg| %>
		<%= content_tag :div, msg, id: "flash_#{name}" %>
		<% end %>
		 
		<%= yield %>

	</div> <!--/.main -->

</body>
</html>

app/views/links/_form.html.erb
<%= form_for([@bundle, @link]) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  
  <div class="actions">
    <%= f.submit nil, class: "button" %>
  </div>
<% end %>

app/views/links/edit.html.erb
<% content_for :header do %>
<header>
	<h2>Editing link</h2>
</header>
<% end %>

<%= render 'form' %>

<hr>

<p>
	<%= link_to 'Show', [@bundle, @link] %>
	<%= link_to 'Destroy', [@bundle, @link], method: :delete, data: { confirm: 'Are you sure?' } %> |
	<%= link_to 'Back', bundle_path(@bundle) %>
</p>

app/views/links/index.html.erb
<h1>Listing links</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Bundle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.name %></td>
        <td><%= link.url %></td>
        <td><%= link.bundle.name %></td>
        <td><%= link_to 'Show', [@bundle, link] %></td>
        <td><%= link_to 'Edit', edit_bundle_link_path(@bundle, link) %></td>
        <td><%= link_to 'Destroy', [@bundle, link], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_bundle_link_path %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render 'form' %>

<%= link_to 'Back', bundle_links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @link.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @link.url %>
</p>

<p>
  <strong>Bundle:</strong>
  <%= @link.bundle_id %>
</p>

<%= link_to 'Edit', edit_bundle_link_path(@bundle, @link) %> |
<%= link_to 'Back', bundle_links_path %>

app/views/users/index.html.erb
<% content_for :header do %>
	<header>
		<h2><%= icon 'user' %> Users</h2>
	</header>
<% end %>


<% @users.each do |user| %>
	<p>
		<strong><%= user.full_name %></strong><br>
		<small>
			<%= user.email %><br>
			<%= user.role_name %>
		</small>
	</p>

<% end %>

<hr>

<p><%= link_to icon('plus-circle') + 'Add new user', new_user_path, class: "button" %></p>

app/views/users/new.html.erb
<% content_for :header do %>
  <header>
    <h2><%= icon 'user' %> New User</h2>
  </header>
<% end %>


<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions"><%= f.submit "Create User", class: "button"  %></div>
<% end %>